# Understanding of this notebook 
So this notebook is intended to serve as a step by step guide-refresher, to be used when designing low level neural networks. 
Low level neural networks  refer to creating matrixes and vectors for the operations inside the neurons, on a manual manner, not utilizing high level packages like keras or scikit-learn, but rather, low level ones like tensorflow or pure numpy. Here we are going to re-read notes on matrix multiplication and linear algebra, and how operation happens in dense neural networks. 

the images used and thee explanation is greatly based of this linear algebra post https://towardsdatascience.com/linear-algebra-cheat-sheet-for-deep-learning-cd67aba4526c
https://matplotlib.org/2.1.1/gallery/mplot3d/scatter3d.html
https://www.youtube.com/watch?v=fNk_zzaMoSs&list=PLZHQObOWTQDPD3MizzM2xVFitgF8hE_ab

# Remembering the linear algebra 

## Vectors 

Vectors are 1-dimensional arrays of numbers or terms.Basically, we can think of them as a  one dimensional list of values. As such, they can be represented in a plane, as changes that can happen to points. Vectors store the magnitude and direction of a potential change to a point. The vector [5, -2] says "go right 3 and down 2", this only can be understood as such in a two dimensional plane, for this particular vector, only  being graphically presentable in two dimensions. Consequently, a vector [3,-2, 5] could only be represented as a potential change to a point in a three dimensional plane. 


To represent graphically, the essence of what a vector represents, we use the origin coordinate to specify him. But in truth, it can be used anywhere on the plane. 


<img src="images/vectors in a graph.png">

Consequently, a vector A = [2,1, 3] could only be represented as a potential change to a point in a three dimensional plane. 


<img src="images/3dvector.png" style="width: 600px;">

Note that we  use the origin, as main support to represent the vector, we could represent it from anywhere though. 


Formally, they can be presented in this different forms, but they all represent the same  


<img src="images/vectorforms.png">

Of course, vectors can be operated on, as objects designed to store numerical information, and possible mathematical forces , we can operate on them to combine them or be affected by other vectors or by simple numbers (scalars). 

Addying, multyplying, dividing or subtracting a scalar to a vector, means executing that operation on each element of the vector individually.

<img src="images/vectorsaddition.png">

On the other hand , addying, multyplying, dividing or subtracting a a vector to a vector, means  executing the operatinon on their equivalent positioned parameters 

<img src="images/vector elementwise addition.png">

If we remember, vectors are forces inside dimensional planes, where each of the elements represents a value for each of the dimensions of said plain (this is the reason why a two valued vector, can only be graphically  represented in two dimensional graphs/planes) , basically operations between vectors cause for the vectors  corresponding values for each dimension, affect their counterparts on the second vector.

The vector also have anothery possible way to multiply each other, the dot  product, that reduces all the information condensed in both lists of values, into one unique number 

<img src="images/vectordotproduct.png">


### Some python examples with numpy, on vector operation

In [14]:
# Python exampple 
import numpy as np

# creating vectors 
y = np.array([1,2,3])
x = np.array([2,3,4])

# creating basic vector to vector operations
op1 = y + x 
op2 = y - x 
op3= x / y 


print(op1)
print(op2)
print(op3)

[3 5 7]
[-1 -1 -1]
[2.         1.5        1.33333333]


In [15]:
# creating basic vector to scalar operations 
op4 = x * 7
op5 = y / 9
print(op4)
print(op5)

[14 21 28]
[0.11111111 0.22222222 0.33333333]


In [16]:
# creating dot products for vectors 
op6  = np.dot(y,x)
print(op6)

20


Vectors, as a list of values regarded to different dimensions of variables, can also be seen as a coordinate, in other words, a point in a graphical representation.  But they are not frequently used as such in linear algebra , the reason being that they allow for more efficient calculation, when stored in groups of vectors inside of matrix .Vectors are interesting to represent and take into consideration, when we see them as forces that affect matrixes, thanks to this, we can use them to calculate in a very fast and efficient manner, functions and complex mathematical calculations. 

If you think about it, it makes sense, imagine I have a coordinate [3,7,5] and I add to it, the effect of the other coordinate, [2,5,9] , in essence, both things are vectors, and both, at the same time are potential changes of direction to each other. 

## Matrixes 

Matrixes are a different form of grouping information that organizes values in  a two dimensional object , you could consider them a  cluster of vectors, organized in groups. A grid of values (more than one list) organized in  categories/atributes/groups/classes or whatever separation criterion you could think of.The two dimensions are rows and columns. In the sense of data and value organizations, matrix essentially represent vectors ( either the rows, or columns can be seen as  vectors )  grouped or categorized in colums or rows. 


<img src="images/formalmatrix1.png" style="width: 400px;">

Because of this two dimensional definition, you could say that actually, we have the potential to organize values based on two classification criterion, one regarding what it means for values to be in separate rows, and one for values to be in separate columns. Basically, not only do we have  many vectors now, we have a mean to differentiate them.

Conventionally, in data analysis, we use the rows to represent each of the samples of our data, each interaction of data gathering, and the columns are used to represent each one a variable of study, a variable whose data we gathered in each interaction. Mathematically, this will correspond to a dimension in a plane.  


In this way, if we had in vectors that each value was correspondant to a dimension/variable in a ndimensional plane, in a matrix each column represents a correspondent dimension/variable and reach row, a list of values each with a sample value of said dimensions. 




Because of this fundamental difference, in the way matrix serve to store information , they  can't be represented in a graph the same way vectors are, matrix therefore don't signify potential changes to a point, but rather, are just an organization of  different points  corresponding to different variables that are potentially related to each other.  A matrix, is sinonym to just, points in a graph. A matrix of nrows, and three columns, could be represented in a three dimensional plane. Like this one 

<img src="images/matrix grapichally.png" style="width: 400px;">


Here, the rows would represent the number of values for each dimension, and the columns, the dimensions themselves. This would mean that each and everyone of the rows ( with one value for each column) represents a point in the graph . On consequence, a  matrix, of n rows, and 2 two collumns, would be represented like this. 


<img src="images/twodmatrix.png" style="width: 400px;">

## Matrix operations 

Matrixes of course as data storing units, can be affected and operated upon. Just like vectors, and scalars, and any mathematical representation of reality. And this is very important because, computanionally, they represent the fastest olbject to wich computers can operate on.


We can add, multiply, divide and subtract scalars the same way we did with vectors, we execute the operation with each element individually, resulting in a new matrix of the same dimensions as the previous one. 

<img src="images/matrix scalar operations.png" style="width: 300px;">

Matrixes, can also be added, subtracted divided and multiplied with other matrixes, in an element wise fashion, we have to remember that at the end of the day, matrixes are clasifying values in different variables and groups, usually the colums represent the variables, and the rows represent groups related to the interaction of the data gather, though they could mean other things ( the rows could mean one type of classification and the columns a different type of classification) , or even, columns could be interactions and rows could be variables.Whatever the case, elementwise operations between matrixes are possible, but can only happen between matrixes with the same dimensions.

<img src="images/matrix elementwiseproduct.png" style="width: 600px;">

Matrixes also allow to realize dot product multiplication, allowing to sinthethize the information of both matrixes in a sigle object. This allows also tu multiply matrixes that don't have the same dimensions. There are some rules though to this process:

1)The number of columns of the 1st matrix must equal the number of rows of the 2nd.
2)The product of an M x N matrix and an N x K matrix is an M x K matrix. The new matrix takes the rows of the 1st and columns of the 2nd


We execute the operation, where each element of each  row, read from the top to the bottom ( first row is the top row, and last row is the bottom row ) is multiplied by each element from each column read from left to right ( first column is further left, and last column is further to the right) 






<img src="images/matrixdotproduct.png" style="width: 600px;">

### Some python examples with numpy, on matrix operation

In [22]:
a = np.array( #creates a 2x2 matrix
[[1,2], 
 [3,4]])


aplus1 = a + 1 #adds scalar

print("aplus1's matrix dimensions are " + str(aplus1.shape))
print(aplus1)

aplus1's matrix dimensions are (2, 2)
[[2 3]
 [4 5]]


In [21]:
a = np.array(  # creates a 2x2 matrix
[[2,3],
 [2,3]])
b = np.array(  # creates another 2x2 matrix
[[3,4],
 [5,6]])


ab= a * b   # multiplies them 



print("ab's matrix dimensions are " + str(ab.shape))
print(ab)

ab's matrix dimensions are (2, 2)
[[ 6 12]
 [10 18]]


In [20]:
#Dot product examples 
a = np.array([
 [1, 2]
 ])  # this will create a matrix of one row, and two columns. It could be considered a vector also

b = np.array([ # a matrix of two rows and two columns 
 [3, 4],
 [5, 6]
 ])


mm = np.dot(a,b) # we calculate the dot product 
print("a's matrix dimensions are " + str(a.shape))
print("b's matrix dimensions are " + str(b.shape))

print("mm's matrix dimensions are " + str(mm.shape))

print(mm)


a's matrix dimensions are (1, 2)
b's matrix dimensions are (2, 2)
mm's matrix dimensions are (1, 2)
[[13 16]]


## Graphically understanding vector operations in a plane 


### Vector element wise operations 

Vector element wise addition, is equivalent to  moving in the direction of the vector inside a plane, and then, moving in the direction of the second vector.  Basically, like moving in the direction dimension( vector 1dimension1 + vector 2 dimension1 ) and then vector1 dimension 2 + vector 2 dimension 2). 

The same principle of change can be applied with element wise multiplication, divition, substraction etc. 


<img src="images/vectorgraphicadd.png" style="width: 600px;">


### Vector scalar operation 

corresponds to basically, expanding the effect the movement of the vector has, by adding / multiplying / dividing, the value of the scalar to itself. 




<img src="images/vectorscalaropgraph.png"  style="width: 500px;">

### Vector dot product 

Introduction
The dot product is a value expressing the angular relationship between two vectors.
A dot product is a scalar value that is the result of an operation of two vectors with the same number of components.  Given two vectors A and B each with n components, the dot product is calculated as:

A · B = A1B1 + ... + AnBn

The dot product is thus the sum of the products of each component of the two vectors. 

<img src="images/dotproduct1.png" style="width: 600px;">


 Its equivalent to projecting one vector onto the other, ,ultiplying the length of the projected vector,with the length of the vector that its projected into.
 
<img src="images/dotporductvectors.png" style="width: 600px;">


### Vector * Matrix dot product 

 If matrixes are simply, are  groups of lists  containing different values , where said values correspond to different dimensions, ( points in a graph) and a vector, is a list of values (that correspond to the graphical representation of potential effects and changes, that can affect each and every point, inside a graph , aka, each list of values in a matrix ). Matrixes, with vectors, represent functions.

f(x) = 236 x + 456 y + 376 z, this mathematically means that x , y and z affect the f(x) by multiplying 236 to the x values, 456 to the y and 376 to the z. In other words 

F(x) will be a matrix, representing all the list of values we can come up  or gather for x,y,z multiplied by a vector [236,456,376]




<img src="images/vectorsandmatrrixfunct.png" style="width: 600px;">