## Using tensorflow to create dense neural networks

Up until now, we have been exposing how the forward propagation works, but as you may have noticed designing the matrixes for every subject case we work with, is a real headache, besides that here we are not taking into account the gradient descent and backpropagation part of it. 
We are going to do that, with tensorflow low level library. 

https://www.tensorflow.org/guide/feature_columns

https://jacobbuckman.com/post/tensorflow-the-confusing-parts-1/
    
https://datascience.stackexchange.com/questions/29863/difference-between-indicator-column-and-categorical-identity-column-in-tensorflo
   
https://stackoverflow.com/questions/46423156/what-is-this-feature-column-and-how-does-it-affect-the-training

https://www.tensorflow.org/api_docs/python/tf/feature_column/numeric_column


http://adventuresinmachinelearning.com/python-tensorflow-tutorial/ 

Tensorflow is basically a language for doing complex operations on multidimensional array like objects, called tensors. With it, we are able to organize complex computations, that allow us to build in a low level library complex machine learning models, like for example neural networks.

We know what vectors and matrixes are right? They are objects for information storage, that are comprised of one and two dimensions respectively. The tensor, is an object that essentially fulfills the same utility, but with the detail that is able to store as many dimensions of data, as needed,being able to maintain it's properties for calculus , while increasing the number of dimensions that we take in consideration when defining the values of the data. 

Dimensions are interesting, in the sense that the more we take in consideration, the bigger picture we take when considering the relationship between different events. mathematically speaking, would be the equivalent of knowing that x and y equal 2 and 4, vs knowing that they equal two and 4 when z equaled 8.Basically, we are having a bigger understanding of the world. This nature for mathematics are what tensor reflect, essentially being a multiway array of data. 

A one dimensional tensor would be a vector, a two dimensional vector would be seen as a matrix, a 3rd dimensional one would be seen as a cube , ( different categories of matrixes) , a 4d tensor would be a list of cubes (groups of categorized matrixes),  a 5th dimensional vector would be analyzing cubes withing two dimensions ( a matrix of cubes ) and so on. 

<img src="tensorimages/tensor.png"   style="width: 600px;"> 

As we mentioned, tensorflow is a language that allows to organize calculations and computations for this objects, in an organized manner. That organization of operations are called graphs, think of them as a canvas that represent all the conections and operationsthat the different tensors will perform to each other and that ultimately, will represent our algorithm,our supervised learning model. 

## Creating tensors 

We have different methods to do so: 

First, we impor the package using import tensorflow as tf , all the method we call will work thanks to us specifying that they come from this package. 

After that, we call the objects, by defining them  

esentially: tf.constant() , tf.variable() and tf.placeholder()

### tf.constant()
This will create a tensor which numerical values, are formed by constant,natural numbers.
 Creating a tensor like this is the same as specifying a storage unit of n dimensions, whos values
 remain the same through time as normal numbers
 
Args:
value: A constant value (or list) of output type dtype.

dtype: The type of the elements of the resulting tensor.

shape: Optional dimensions of resulting tensor.

name: Optional name for the tensor.

verify_shape: Boolean that enables verification of a shape of values.


More details here. https://www.tensorflow.org/api_docs/python/tf/constant

In [11]:
import numpy as np
import tensorflow as tf


# Constant 1-D Tensor populated with value list.
constant_tensor1 = tf.constant([1, 2, 3, 4, 5, 6, 7]) 

# Constant 2-D tensor populated with scalar value -1.
constant_tensor2 = tf.constant(-1.0, shape=[2, 3]) 


print(constant_tensor1)
print(constant_tensor2)

tf.Tensor([1 2 3 4 5 6 7], shape=(7,), dtype=int32)
tf.Tensor(
[[-1. -1. -1.]
 [-1. -1. -1.]], shape=(2, 3), dtype=float32)


Basically, we created a vector and a matrix. Tensors in their own right formed by constant variables. 

### tf.variable()

This on the other hand, creates a tensor also with numerical values, but this ones are 
recongized as ones that can have different values through different instances.

The Variable() constructor requires an initial value for the variable, which can be a Tensor of any type and shape. The initial value defines the type and shape of the variable. After construction, the type and shape of the variable are fixed. The value can be changed using one of the assign methods.

Its main arguments are the initial value of the variable and a name, the initial value can be a tensor of any size. 

Details : https://www.tensorflow.org/api_docs/python/tf/Variable

In [23]:
import tensorflow as tf

# Create a variable.
w = tf.Variable(36, name='w') # this for example, will create a zero dimensional tensor, a scalar.

w_matrix = tf.Variable(np.array([[4,5,6],[6,8,9]]) , name = 'w_matrix')# we create a tensor
# matrix 



print(w)
print(w_matrix)

<tf.Variable 'w:0' shape=() dtype=int32, numpy=36>
<tf.Variable 'w_matrix:0' shape=(2, 3) dtype=int64, numpy=
array([[4, 5, 6],
       [6, 8, 9]])>


 The advantage the variable tensor offers, it's that we can apply methods to update it's value for example , the assign method.

In [26]:
w.assign(w + 1)
w_matrix.assign(w_matrix + 6)  

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=int64, numpy=
array([[10, 11, 12],
       [12, 14, 15]])>

### tf.placeholder()

This creates tensors formed by objects that are like variables, with the main difference that they don't own an initial value. Basically when creating them, we are declaring  as "reserved" a memory space that will be filled in the future, with values. The reason we do this is because sometimes, we create first our neural network architecture before loading the data to it. Or we have different criterias as how we want to initialize values ( for example, to avoid exploding and vanishing gradients) 

https://www.tensorflow.org/api_docs/python/tf/placeholder


In [34]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()


x = tf.placeholder(tf.float32, shape=(1024, 1024)) # We declare the placeholder, no value
#stored yet just on this command

rand_array = np.random.rand(1024, 1024) # the vector containing the data we will put in the
# placeholder, a random generated array

print(x) # If we print this, nothing will be seen inside X , just a placeholder. 

Tensor("Placeholder_4:0", shape=(1024, 1024), dtype=float32)


In [35]:
with tf.Session() as sess: # We define a session, to start introducing the data 
    print(sess.run(x, feed_dict={x: rand_array})) # The method to introduce the data.

[[0.9240374  0.47898015 0.11209893 ... 0.28928065 0.27164865 0.3012986 ]
 [0.37938744 0.73697186 0.03840093 ... 0.6313227  0.20122004 0.06329225]
 [0.35414892 0.08874901 0.24399182 ... 0.06801349 0.57358205 0.8249495 ]
 ...
 [0.6798764  0.9643369  0.9761579  ... 0.06170417 0.7129313  0.3940755 ]
 [0.6961393  0.27441642 0.21745612 ... 0.3125642  0.21894976 0.7965268 ]
 [0.17955014 0.38402048 0.6208931  ... 0.29515657 0.8132611  0.93698454]]


## Operations 

So thats how we create tensors, cool, but how do we operate them? We utilize operation objects,graphs and sessions to do so.Basically,  they are just objects that represent the operation that ocurrs,this allows us to organize operations by name and interchange their sequential order, when building models. Some examples are this 

tf.math.add()
tf.math.subtract()

Now, basically operations require not only for us to store the object, but also, to create a session to execute it. The reason for this is because that way we can work on the model design without having to worry on consumed ram. 

Also, sessions, as a good practice, are thougth to be closed after executing the operation.

In [37]:
constant_tensor2 = tf.constant(-1.0, shape=[2, 3]) 

constant_tensor3 = tf.constant(3.0, shape=[2, 3]) 

a = tf.math.add(constant_tensor2,constant_tensor3, name = None) # define tensor operation
b = tf.math.subtract(constant_tensor2,constant_tensor3, name = None) # define tensor operation

# If we call them, we see that we will only have the object. 
print(a)
print(b)

Tensor("Add_1:0", shape=(2, 3), dtype=float32)
Tensor("Sub_1:0", shape=(2, 3), dtype=float32)


To see the result, we need to create a session object, and run the operation as an instance of said session

In [39]:
mathexamples = tf.Session() # We define session object
mathexamples.run(a) # We run the operation object, inside the session object. 

array([[2., 2., 2.],
       [2., 2., 2.]], dtype=float32)

In [40]:
mathexamples.run(b)

array([[-4., -4., -4.],
       [-4., -4., -4.]], dtype=float32)

In [41]:
mathexamples.close  # We close the session

<bound method BaseSession.close of <tensorflow.python.client.session.Session object at 0x7f57084b12e8>>

## Graphs

Now, operations are thought to be done in sequential order, allowing us to organize many complex procedures with these system. There is another advantage to working with them in this manner, and that is the graphs. A computational graph is a series of TensorFlow operations arranged in a sequential manner. Think of it like the mental map you have in mind when designing the architecture of the model or series of operations that you are creating, only that now, it is not only mental. The graph basically classifies the objects inside the code you write, in  into two objects.tf.Operation (or "ops") and  tf.Tensor and draws them in a diagram. 

Basically, if until now you understood sequences of operations organized from directly the code, now you can understand them drawn in a diagram, tensorflow will gather the operations and tensors produced in your session , that you declared as code, and draw it in a diagram. In that diagram, the operations will be presented as nodes, and the tensors as the edges of the graph. Lets see an example. 

Lets call again some tensors and operate on them

In [42]:
constant_tensor2 = tf.constant(-1.0, shape=[2, 3]) 

constant_tensor3 = tf.constant(3.0, shape=[2, 3]) 

constant_tensor5 = tf.constant(10.0, shape=[2, 3]) 

a = tf.math.add(constant_tensor2,constant_tensor3, name = None) # define tensor operation
b = tf.math.subtract(constant_tensor2,constant_tensor3, name = None)

c = tf.math.add(a,constant_tensor5, name = None)# define tensor operation


Tensor("Add_2:0", shape=(2, 3), dtype=float32)
Tensor("Sub_2:0", shape=(2, 3), dtype=float32)


In [54]:
mathegraphxamples = tf.Session() # We define session object and run operations
mathegraphxamples.run(a)
mathegraphxamples.run(b)
mathegraphxamples.run(c)

array([[12., 12., 12.],
       [12., 12., 12.]], dtype=float32)

In [55]:
%load_ext tensorboard.notebook # We  prepare our jupyter notebook to load the tensorboard
tf.summary.FileWriter('./examplegraph',mathegraphxamples.graph) # we create our graph , 
# summarizing our sessions operations

In [56]:
%tensorboard --logdir ./examplegraph  # call our graph for seeing


In [57]:
mathegraphxamples.close()



## Creating an actual neural network

So we know the basics now, essentially, this is what tensorflow is all about in a low level, 
it will from here get as harder as the models you try to train inside of them. To end this 
Wonderfull tutorial, let's see how a neural network is trained inside of here. 

### Import the data 

In [159]:
import pandas as pd

df= pd.read_csv('/home/nacho/Descargas/datasets/heart-disease-uci/heart.csv' 
               )

In [160]:
# Now lets shuffle it in a training and test set 

In [161]:
from sklearn.utils import shuffle
from sklearn.model_selection import train_test_split
import numpy as np
import tensorflow as tf
import tensorflow.compat.v1 as tf

tf.disable_v2_behavior()



In [162]:
X = df.drop('target', axis = 1)

Y = df["target"]

In [163]:
X,Y = shuffle (X, Y, random_state = 0)

train_x, test_x, train_y, test_y = train_test_split(X, Y, test_size = 0.20, random_state = 0)

### Define Neural network architecture

In [177]:
# The learning rate we want for our gradient descent, and the number of epochs
# We want to use to train our data

learning_rate = 0.2
training_epochs = 100 

# The number of layers we want, with the number of neurons we want them 
n_hidden_1 = 60
n_hidden_2 = 60
n_hidden_3 = 60
n_hidden_4 = 60

# Define cost function and training algorithm 

costf = 'cross entropy'
traininga = "gradient descent optimizer"



### Create the objects that will be placed inside the neural network 

In [178]:
X.shape[1]

13

In [179]:
# We define the inputs as placeholder, we shall fill them when we execute our code
n_dim = X.shape[1] # This will help define the vectors and matrices for calculation correctly
n_class = 1 # The number  of categorie values possibles for Y 



#We need to solve the nlen thing 


x = tf.placeholder(tf.float32)   # Specifying where we are going to put the vectors 
y_ = tf.placeholder(tf.float32)


# We define out weights and bias as variables also
W = tf.Variable(tf.zeros([n_dim, n_class]))
b = tf.Variable(tf.zeros([n_class]))





In [180]:
# We define the weights as code,  we use the different input and each layers neurons as the dimensions
# of the tensors we are creating  
# We use truncated_normal to generate random values that are normal but also truncated, because we 
# want to use a sigmoid function, and thus avoid oversaturation.  We can use tf.random_normal when using a 
# relu function as activation 


weights = {
    'h1': tf.Variable(tf.truncated_normal([n_dim, n_hidden_1])),
    'h2': tf.Variable(tf.truncated_normal([n_hidden_1, n_hidden_2])),
    'h3': tf.Variable(tf.truncated_normal([n_hidden_2, n_hidden_3])),
    'h4': tf.Variable(tf.truncated_normal([n_hidden_3, n_hidden_4])),
    'out': tf.Variable(tf.truncated_normal([n_hidden_4, n_class]))
}

In [181]:
# Define the bias for each layers

biases = {
    'b1': tf.Variable(tf.truncated_normal([n_hidden_1])),
    'b2': tf.Variable(tf.truncated_normal([n_hidden_2])),
    'b3': tf.Variable(tf.truncated_normal([n_hidden_3])),
    'b4': tf.Variable(tf.truncated_normal([n_hidden_4])),
    'out': tf.Variable(tf.truncated_normal([n_class]))
}

### Define the model

In [182]:
# Defining the model 

def multilayer_perceptron(x, weights, biases):
 
    # Hidden layer with RELU activationsd
    layer_1 = tf.add(tf.matmul(x, weights['h1']), biases['b1']) # We first multiply, and then add bias
    layer_1 = tf.nn.relu(layer_1)
 
    # Hidden layer with sigmoid activation
    layer_2 = tf.add(tf.matmul(layer_1, weights['h2']), biases['b2'])
    layer_2 = tf.nn.relu(layer_2)
 
    # Hidden layer with sigmoid activation
    layer_3 = tf.add(tf.matmul(layer_2, weights['h3']), biases['b3'])
    layer_3 = tf.nn.relu(layer_3)
 
    # Hidden layer with RELU activation
    layer_4 = tf.add(tf.matmul(layer_3, weights['h4']), biases['b4'])
    layer_4 = tf.nn.sigmoid(layer_4)
 
    # Output layer with linear activation
    out_layer = tf.matmul(layer_4, weights['out']) + biases['out']
    return out_layer


# Calling model
y = multilayer_perceptron(x, weights, biases) # Basically, this will execute all our layers computations, resulting
# in a tensor y with our predicted results. 

In [183]:
# Defining function and training step 
cost_function = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits(logits=y, labels=y_)) #  Calculates the cross_entropy 
training_step = tf.train.GradientDescentOptimizer(learning_rate).minimize(cost_function) # Executes the gradient descent optimizer


### Define extra variables and functions of interest: 

In [184]:
# We are going to create lists, that will allow us to plot the evolution of the epochs accuracy and error after traini
mse_history = []
accuracy_history = []
cost_history = []

### Execute the model 

In [185]:
# We will define an operation that will initialize variables inside the graph. This is always necesary if we
# called tensor variables 
init = tf.global_variables_initializer()  

# The session object we are going to need for execution 
sess = tf.Session()
sess.run(init)  # We initialize the global variables

## Test 1: using values 

In [186]:
for epoch in range(training_epochs):
    sess.run(training_step, feed_dict = {x: train_x.values, y_: train_y.values})  # We start with the training
    cost = sess.run(cost_function, feed_dict={x: train_x.values, y_: train_y.values}) #We calculate the loss for that epoch
    cost_history = np.append(cost_history, cost) # With that loss calculted we append it to a list
    correct_prediction = tf.equal(tf.argmax(y, 1), tf.argmax(y_, 1))  # We calculate what would be the correct prediction
    accuracy = tf.reduce_mean(tf.cast(correct_prediction, tf.float32)) # We define a function to calculate accuracy 
    pred_y = sess.run(y, feed_dict = {x: test_x.values}) # Predict after training in the epoch
    mse = tf.reduce_mean(tf.square(pred_y - test_y.values)) # define a function to Calculate the error of that epoch
    mse_ = sess.run(mse)  # we run said function
    mse_history.append(mse_)  # We append the result to a list
    print(epoch)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99


In [ ]:
# If we use accuracy, we get error 

In [176]:
for epoch in range(training_epochs):
    sess.run(training_step, feed_dict = {x: train_x.values, y_: train_y.values})  # We start with the training
    cost = sess.run(cost_function, feed_dict={x: train_x.values, y_: train_y.values}) #We calculate the loss for that epoch
    cost_history = np.append(cost_history, cost) # With that loss calculted we append it to a list
    correct_prediction = tf.equal(tf.argmax(y, 1), tf.argmax(y_, 1))  # We calculate what would be the correct prediction
    accuracy = tf.reduce_mean(tf.cast(correct_prediction, tf.float32)) # We define a function to calculate accuracy 
    pred_y = sess.run(y, feed_dict = {x: test_x.values}) # Predict after training in the epoch
    mse = tf.reduce_mean(tf.square(pred_y - test_y.values)) # define a function to Calculate the error of that epoch
    mse_ = sess.run(mse)  # we run said function
    mse_history.append(mse_)  # We append the result to a list
    accuracy = (sess.run(accuracy, feed_dict={x: train_x.values, y_: train_y.values})) # Execute the accuracy function
    accuracy_history.append(accuracy) 

InvalidArgumentError: Expected dimension in the range [-1, 1), but got 1
	 [[node ArgMax_1561 (defined at <ipython-input-176-fc9234678b87>:5) ]]

Errors may have originated from an input operation.
Input Source operations connected to node ArgMax_1561:
 Placeholder_19 (defined at <ipython-input-166-844432d3b8cf>:11)

Original stack trace for 'ArgMax_1561':
  File "/home/nacho/anaconda3/envs/deepl1/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/nacho/anaconda3/envs/deepl1/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/nacho/anaconda3/envs/deepl1/lib/python3.6/site-packages/ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "/home/nacho/anaconda3/envs/deepl1/lib/python3.6/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/home/nacho/anaconda3/envs/deepl1/lib/python3.6/site-packages/ipykernel/kernelapp.py", line 505, in start
    self.io_loop.start()
  File "/home/nacho/anaconda3/envs/deepl1/lib/python3.6/site-packages/tornado/platform/asyncio.py", line 148, in start
    self.asyncio_loop.run_forever()
  File "/home/nacho/anaconda3/envs/deepl1/lib/python3.6/asyncio/base_events.py", line 438, in run_forever
    self._run_once()
  File "/home/nacho/anaconda3/envs/deepl1/lib/python3.6/asyncio/base_events.py", line 1451, in _run_once
    handle._run()
  File "/home/nacho/anaconda3/envs/deepl1/lib/python3.6/asyncio/events.py", line 145, in _run
    self._callback(*self._args)
  File "/home/nacho/anaconda3/envs/deepl1/lib/python3.6/site-packages/tornado/ioloop.py", line 690, in <lambda>
    lambda f: self._run_callback(functools.partial(callback, future))
  File "/home/nacho/anaconda3/envs/deepl1/lib/python3.6/site-packages/tornado/ioloop.py", line 743, in _run_callback
    ret = callback()
  File "/home/nacho/anaconda3/envs/deepl1/lib/python3.6/site-packages/tornado/gen.py", line 781, in inner
    self.run()
  File "/home/nacho/anaconda3/envs/deepl1/lib/python3.6/site-packages/tornado/gen.py", line 742, in run
    yielded = self.gen.send(value)
  File "/home/nacho/anaconda3/envs/deepl1/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 357, in process_one
    yield gen.maybe_future(dispatch(*args))
  File "/home/nacho/anaconda3/envs/deepl1/lib/python3.6/site-packages/tornado/gen.py", line 209, in wrapper
    yielded = next(result)
  File "/home/nacho/anaconda3/envs/deepl1/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 267, in dispatch_shell
    yield gen.maybe_future(handler(stream, idents, msg))
  File "/home/nacho/anaconda3/envs/deepl1/lib/python3.6/site-packages/tornado/gen.py", line 209, in wrapper
    yielded = next(result)
  File "/home/nacho/anaconda3/envs/deepl1/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 534, in execute_request
    user_expressions, allow_stdin,
  File "/home/nacho/anaconda3/envs/deepl1/lib/python3.6/site-packages/tornado/gen.py", line 209, in wrapper
    yielded = next(result)
  File "/home/nacho/anaconda3/envs/deepl1/lib/python3.6/site-packages/ipykernel/ipkernel.py", line 294, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "/home/nacho/anaconda3/envs/deepl1/lib/python3.6/site-packages/ipykernel/zmqshell.py", line 536, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "/home/nacho/anaconda3/envs/deepl1/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2848, in run_cell
    raw_cell, store_history, silent, shell_futures)
  File "/home/nacho/anaconda3/envs/deepl1/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2874, in _run_cell
    return runner(coro)
  File "/home/nacho/anaconda3/envs/deepl1/lib/python3.6/site-packages/IPython/core/async_helpers.py", line 67, in _pseudo_sync_runner
    coro.send(None)
  File "/home/nacho/anaconda3/envs/deepl1/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 3049, in run_cell_async
    interactivity=interactivity, compiler=compiler, result=result)
  File "/home/nacho/anaconda3/envs/deepl1/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 3214, in run_ast_nodes
    if (yield from self.run_code(code, result)):
  File "/home/nacho/anaconda3/envs/deepl1/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 3296, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-176-fc9234678b87>", line 5, in <module>
    correct_prediction = tf.equal(tf.argmax(y, 1), tf.argmax(y_, 1))  # We calculate what would be the correct prediction
  File "/home/nacho/anaconda3/envs/deepl1/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/home/nacho/anaconda3/envs/deepl1/lib/python3.6/site-packages/tensorflow/python/ops/math_ops.py", line 137, in argmax
    return argmax_v2(input, axis, output_type, name)
  File "/home/nacho/anaconda3/envs/deepl1/lib/python3.6/site-packages/tensorflow/python/ops/math_ops.py", line 166, in argmax_v2
    return gen_math_ops.arg_max(input, axis, name=name, output_type=output_type)
  File "/home/nacho/anaconda3/envs/deepl1/lib/python3.6/site-packages/tensorflow/python/ops/gen_math_ops.py", line 938, in arg_max
    name=name)
  File "/home/nacho/anaconda3/envs/deepl1/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 800, in _apply_op_helper
    op_def=op_def)
  File "/home/nacho/anaconda3/envs/deepl1/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/home/nacho/anaconda3/envs/deepl1/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3479, in create_op
    op_def=op_def)
  File "/home/nacho/anaconda3/envs/deepl1/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1961, in __init__
    self._traceback = tf_stack.extract_stack()


## Without values 

In [142]:
for epoch in range(training_epochs):
    sess.run(training_step, feed_dict = {x: train_x, y_: train_y})  # We start with the training
    cost = sess.run(cost_function, feed_dict={x: train_x, y_: train_y}) #We calculate the loss for that epoch
    cost_history = np.append(cost_history, cost) # With that loss calculted we append it to a list
    correct_prediction = tf.equal(tf.argmax(y, 1), tf.argmax(y_, 1))  # We calculate what would be the correct prediction
    accuracy = tf.reduce_mean(tf.cast(correct_prediction, tf.float32)) # We define a function to calculate accuracy 
    pred_y = sess.run(y, feed_dict = {x: test_x}) # Predict after training in the epoch
    mse = tf.reduce_mean(tf.square(pred_y - test_y)) # define a function to Calculate the error of that epoch
    mse_ = sess.run(mse)  # we run said function
    mse_history.append(mse_)  # We append the result to a list
    accuracy = (sess.run(accuracy, feed_dict={x: train_x, y_: train_y})) # Execute the accuracy function
    accuracy_history.append(accuracy) # Append the result of the accuracy to a list 

Exception: Data must be 1-dimensional

teorias del error:
    
estamos metiendo los datos en forma de dataframe, cuando son numpy arrays realmente 


 Deberíamos probar con el sistema que utilizan en el curso más aqúi 
https://www.tensorflow.org/tutorials/eager/custom_training_walkthrough 
    


Errores que han surgido 

Cannot feed value of shape (242,) for Tensor 'Placeholder_11:0', which has shape '(242, 2)'


Cannot feed value of shape (242,) for Tensor 'Placeholder_15:0', which has shape '(?, 1)' 